const DATA = {
    "files":[
        {
            "name":"hinomaru"
        },
        {
            "name":"bloom-image"
        },
        {
            "name":"vaporwave-image"
        },
        {
            "name":"spot"
        },
        {
            "name":"neon-text"
        },
        {
            "name":"dynamic-text"
        },
        {
            "name":"text-particle"
        },
        {
            "name":"wave-pattern"
        },
        {
            "name":"rotate-shape"
        },
        {
            "name":"culture-microorganism"
        },
        {
            "name":"grid-line-circle"
        },
        {
            "name":"rough-squares"
        },
        {
            "name":"flashlight"
        },
        {
            "name":"pursuit-bubbles"
        },
        {
            "name":"shadow-circle"
        },
        {
            "name":"free-particle"
        },
        {
            "name":"grid-particle-line"
        }
    ]
};